

POST http://localhost:8080/game
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name": "James", "hardware": "Smith","release_date" : "1980-01-01T00:00:01","software_ids":[1],"studio_id": 1}

###

POST http://localhost:8080/location
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"state": "testaste", "town": "Wayne","address": null}

###

POST http://localhost:8080/studio
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name": "My Book", "founding_date": "1980-01-01T00:00:01", "Location_id":2}


###

/**GET ++*/